# Generated by Django 4.2.3 on 2023-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
